import { ILlmProvider, LlmMessage, LlmResponse } from './ILlmProvider';
import { BaseTool } from '../tools/BaseTool';

export class MockProvider implements ILlmProvider {
    async generateContent(systemPrompt: string, history: LlmMessage[], tools?: BaseTool[] | undefined): Promise<LlmResponse> {
        if (systemPrompt.includes('skillId')) {
            // Routing prompt expects JSON
            if (history[0]?.content.includes('test skill')) {
                return { content: JSON.stringify({ skillId: 'test-skill' }) };
            }
            if (history[0]?.content.includes('edital') || history[0]?.content.includes('riscos')) {
                return { content: JSON.stringify({ skillId: 'legal-document-explainer-br' }) };
            }
            return { content: JSON.stringify({ skillId: null }) };
        }
        
        return {
            content: "Mock response generated by MockProvider. This confirms the system flow works."
        };
    }
}
